#!/bin/bash
set -e

echo "Running command for extras..."

for project in ./xtra_*; do
  [[ "$project" =~ [^/]*/(.*) ]]
  name="${BASH_REMATCH[1]}"

  echo ""
  echo "Project $name:"

  cd "$project"
  "$@"
  cd ..
done
