#!/bin/bash
set -e

echo "Running git for extras..."

for project in ./xtra.vexyz*; do
  [[ "$project" =~ [^/]*/(.*) ]]
  name="${BASH_REMATCH[1]}"

  echo ""
  echo "Project $name:"

  cd "$project"
  git "$@"
  cd ..
done
