#!/bin/bash
set -e

echo "Cleaning extras..."

for project in ./xtra_*; do
  [[ "$project" =~ [^/]*/(.*) ]]
  name="${BASH_REMATCH[1]}"

  echo "Cleaning $name."

  if [ "$name" == "xtra_website" ]; then
    cd "$project"
    # Nothing to do yet.
    cd ..
  else
    cd "$project"
    rm -rf target
    rm -rf gen/target
    cd ..
  fi
done
