#!/bin/bash
set -e

echo "Backing up vexyz files..."

# Navigate into Vexyz dir.
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$dir"
cd ..

# Archive and backup.
name="$(basename "$PWD")"
timestamp="$(date +%Y%m%d_%H%M%S)"
dest="$HOME/Dropbox/Backup/$name-$timestamp.tar.gz"

tar --exclude='xtra_website' --exclude='*/.git' --exclude='*/target' -zcvf "$dest" "."

echo "Done."
