#!/bin/bash
set -e

echo "Cloning vexyz projects..."

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
targets=$(cat "$dir/targets")

for target in $targets; do
  [[ "$target" =~ ([^\|]*)\|(.*) ]]
  repo="${BASH_REMATCH[1]}"
  branch="${BASH_REMATCH[2]}"

  [[ "$repo" =~ [^/]*/(.*) ]]
  name="${BASH_REMATCH[1]}"

  echo ""
  git clone "$repo"
  cd "$name"
  git checkout "$branch"
  cd ..
done
