#!/bin/bash
set -e

echo "Running command for vexyz projects..."

for project in ./vexyz_*; do
  [[ "$project" =~ [^/]*/(.*) ]]
  name="${BASH_REMATCH[1]}"

  echo ""
  echo "Project $name:"

  cd "$project"
  "$@"
  cd ..
done
